// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeldMKK77sLDlL04FFicwu3pYPVB6EIz4',
    appId: '1:439222343527:web:06ee2dca49f845421901c2',
    messagingSenderId: '439222343527',
    projectId: 'ghmeraapp-aeb79',
    authDomain: 'ghmeraapp-aeb79.firebaseapp.com',
    storageBucket: 'ghmeraapp-aeb79.firebasestorage.app',
    measurementId: 'G-GJRMD9VG4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAya1Np3sp8TG5RsnratB5kFWMn6iGUC7g',
    appId: '1:439222343527:android:5dd908dd9feb02611901c2',
    messagingSenderId: '439222343527',
    projectId: 'ghmeraapp-aeb79',
    storageBucket: 'ghmeraapp-aeb79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeyhG7lAeWl29QnszpxIRMxECbb9TEPrQ',
    appId: '1:439222343527:ios:495dcda1e27382581901c2',
    messagingSenderId: '439222343527',
    projectId: 'ghmeraapp-aeb79',
    storageBucket: 'ghmeraapp-aeb79.firebasestorage.app',
    iosClientId: '439222343527-3n1jp0l99a6e2ojrs1pib10msb3js70v.apps.googleusercontent.com',
    iosBundleId: 'com.peatech.ghmeraApp',
  );

}